// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: notification/notification.proto

package notification

import (
	common "github.com/tolgafiratoglu/mediaflow/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_EMAIL       Channel = 1
	Channel_CHANNEL_WEBHOOK     Channel = 2
	Channel_CHANNEL_PUSH        Channel = 3
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_EMAIL",
		2: "CHANNEL_WEBHOOK",
		3: "CHANNEL_PUSH",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_EMAIL":       1,
		"CHANNEL_WEBHOOK":     2,
		"CHANNEL_PUSH":        3,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notification_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

type DeliveryState int32

const (
	DeliveryState_DELIVERY_STATE_UNSPECIFIED DeliveryState = 0
	DeliveryState_DELIVERY_STATE_QUEUED      DeliveryState = 1
	DeliveryState_DELIVERY_STATE_SENT        DeliveryState = 2
	DeliveryState_DELIVERY_STATE_FAILED      DeliveryState = 3
	DeliveryState_DELIVERY_STATE_DEFERRED    DeliveryState = 4 // circuit breaker open, waiting for retry
)

// Enum value maps for DeliveryState.
var (
	DeliveryState_name = map[int32]string{
		0: "DELIVERY_STATE_UNSPECIFIED",
		1: "DELIVERY_STATE_QUEUED",
		2: "DELIVERY_STATE_SENT",
		3: "DELIVERY_STATE_FAILED",
		4: "DELIVERY_STATE_DEFERRED",
	}
	DeliveryState_value = map[string]int32{
		"DELIVERY_STATE_UNSPECIFIED": 0,
		"DELIVERY_STATE_QUEUED":      1,
		"DELIVERY_STATE_SENT":        2,
		"DELIVERY_STATE_FAILED":      3,
		"DELIVERY_STATE_DEFERRED":    4,
	}
)

func (x DeliveryState) Enum() *DeliveryState {
	p := new(DeliveryState)
	*p = x
	return p
}

func (x DeliveryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_notification_proto_enumTypes[1].Descriptor()
}

func (DeliveryState) Type() protoreflect.EnumType {
	return &file_notification_notification_proto_enumTypes[1]
}

func (x DeliveryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryState.Descriptor instead.
func (DeliveryState) EnumDescriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

// Delivery is one notification attempt persisted by notification-service.
// It is keyed by (notification_id, channel) so the same business event can
// produce multiple deliveries (e.g. email + webhook).
type Delivery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId        string                 `protobuf:"bytes,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"` // related aggregate
	Channel        Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=mediaflow.notification.Channel" json:"channel,omitempty"`
	State          DeliveryState          `protobuf:"varint,5,opt,name=state,proto3,enum=mediaflow.notification.DeliveryState" json:"state,omitempty"`
	Template       string                 `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"` // e.g. "media.ready"
	LastError      string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Attempt        int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	NextRetryAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Delivery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Delivery) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Delivery) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *Delivery) GetState() DeliveryState {
	if x != nil {
		return x.State
	}
	return DeliveryState_DELIVERY_STATE_UNSPECIFIED
}

func (x *Delivery) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Delivery) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Delivery) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Delivery) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Delivery) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

// SendNotification is mostly used by ops to manually re-send. The normal
// path is event-driven from media.processing.completed/failed topics.
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Channels      []Channel              `protobuf:"varint,4,rep,packed,name=channels,proto3,enum=mediaflow.notification.Channel" json:"channels,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // template variable substitutions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendNotificationRequest) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SendNotificationRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type GetDeliveryStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusResponse) Reset() {
	*x = GetDeliveryStatusResponse{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusResponse) ProtoMessage() {}

func (x *GetDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryStatusResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type NotificationSent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId        string                 `protobuf:"bytes,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Channel        Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=mediaflow.notification.Channel" json:"channel,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationSent) Reset() {
	*x = NotificationSent{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSent) ProtoMessage() {}

func (x *NotificationSent) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSent.ProtoReflect.Descriptor instead.
func (*NotificationSent) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationSent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationSent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationSent) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *NotificationSent) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *NotificationSent) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type NotificationFailed struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel        Channel                `protobuf:"varint,3,opt,name=channel,proto3,enum=mediaflow.notification.Channel" json:"channel,omitempty"`
	Error          *common.Error          `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Attempt        int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationFailed) Reset() {
	*x = NotificationFailed{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationFailed) ProtoMessage() {}

func (x *NotificationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationFailed.ProtoReflect.Descriptor instead.
func (*NotificationFailed) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationFailed) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationFailed) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationFailed) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *NotificationFailed) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *NotificationFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\x16mediaflow.notification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xa9\x03\n" +
	"\bDelivery\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\tR\amediaId\x129\n" +
	"\achannel\x18\x04 \x01(\x0e2\x1f.mediaflow.notification.ChannelR\achannel\x12;\n" +
	"\x05state\x18\x05 \x01(\x0e2%.mediaflow.notification.DeliveryStateR\x05state\x12\x1a\n" +
	"\btemplate\x18\x06 \x01(\tR\btemplate\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x123\n" +
	"\asent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12>\n" +
	"\rnext_retry_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\"\xc2\x02\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12;\n" +
	"\bchannels\x18\x04 \x03(\x0e2\x1f.mediaflow.notification.ChannelR\bchannels\x12\\\n" +
	"\tvariables\x18\x05 \x03(\v2>.mediaflow.notification.SendNotificationRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x18SendNotificationResponse\x12@\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2 .mediaflow.notification.DeliveryR\n" +
	"deliveries\"C\n" +
	"\x18GetDeliveryStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"]\n" +
	"\x19GetDeliveryStatusResponse\x12@\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2 .mediaflow.notification.DeliveryR\n" +
	"deliveries\"\xdf\x01\n" +
	"\x10NotificationSent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\tR\amediaId\x129\n" +
	"\achannel\x18\x04 \x01(\x0e2\x1f.mediaflow.notification.ChannelR\achannel\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xda\x01\n" +
	"\x12NotificationFailed\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\achannel\x18\x03 \x01(\x0e2\x1f.mediaflow.notification.ChannelR\achannel\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x17.mediaflow.common.ErrorR\x05error\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt*\\\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x01\x12\x13\n" +
	"\x0fCHANNEL_WEBHOOK\x10\x02\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x03*\x9b\x01\n" +
	"\rDeliveryState\x12\x1e\n" +
	"\x1aDELIVERY_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DELIVERY_STATE_QUEUED\x10\x01\x12\x17\n" +
	"\x13DELIVERY_STATE_SENT\x10\x02\x12\x19\n" +
	"\x15DELIVERY_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17DELIVERY_STATE_DEFERRED\x10\x042\x86\x02\n" +
	"\x13NotificationService\x12u\n" +
	"\x10SendNotification\x12/.mediaflow.notification.SendNotificationRequest\x1a0.mediaflow.notification.SendNotificationResponse\x12x\n" +
	"\x11GetDeliveryStatus\x120.mediaflow.notification.GetDeliveryStatusRequest\x1a1.mediaflow.notification.GetDeliveryStatusResponseBEZCgithub.com/tolgafiratoglu/mediaflow/proto/notification;notificationb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_notification_proto_goTypes = []any{
	(Channel)(0),                      // 0: mediaflow.notification.Channel
	(DeliveryState)(0),                // 1: mediaflow.notification.DeliveryState
	(*Delivery)(nil),                  // 2: mediaflow.notification.Delivery
	(*SendNotificationRequest)(nil),   // 3: mediaflow.notification.SendNotificationRequest
	(*SendNotificationResponse)(nil),  // 4: mediaflow.notification.SendNotificationResponse
	(*GetDeliveryStatusRequest)(nil),  // 5: mediaflow.notification.GetDeliveryStatusRequest
	(*GetDeliveryStatusResponse)(nil), // 6: mediaflow.notification.GetDeliveryStatusResponse
	(*NotificationSent)(nil),          // 7: mediaflow.notification.NotificationSent
	(*NotificationFailed)(nil),        // 8: mediaflow.notification.NotificationFailed
	nil,                               // 9: mediaflow.notification.SendNotificationRequest.VariablesEntry
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*common.Error)(nil),              // 11: mediaflow.common.Error
}
var file_notification_notification_proto_depIdxs = []int32{
	0,  // 0: mediaflow.notification.Delivery.channel:type_name -> mediaflow.notification.Channel
	1,  // 1: mediaflow.notification.Delivery.state:type_name -> mediaflow.notification.DeliveryState
	10, // 2: mediaflow.notification.Delivery.sent_at:type_name -> google.protobuf.Timestamp
	10, // 3: mediaflow.notification.Delivery.next_retry_at:type_name -> google.protobuf.Timestamp
	0,  // 4: mediaflow.notification.SendNotificationRequest.channels:type_name -> mediaflow.notification.Channel
	9,  // 5: mediaflow.notification.SendNotificationRequest.variables:type_name -> mediaflow.notification.SendNotificationRequest.VariablesEntry
	2,  // 6: mediaflow.notification.SendNotificationResponse.deliveries:type_name -> mediaflow.notification.Delivery
	2,  // 7: mediaflow.notification.GetDeliveryStatusResponse.deliveries:type_name -> mediaflow.notification.Delivery
	0,  // 8: mediaflow.notification.NotificationSent.channel:type_name -> mediaflow.notification.Channel
	10, // 9: mediaflow.notification.NotificationSent.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 10: mediaflow.notification.NotificationFailed.channel:type_name -> mediaflow.notification.Channel
	11, // 11: mediaflow.notification.NotificationFailed.error:type_name -> mediaflow.common.Error
	3,  // 12: mediaflow.notification.NotificationService.SendNotification:input_type -> mediaflow.notification.SendNotificationRequest
	5,  // 13: mediaflow.notification.NotificationService.GetDeliveryStatus:input_type -> mediaflow.notification.GetDeliveryStatusRequest
	4,  // 14: mediaflow.notification.NotificationService.SendNotification:output_type -> mediaflow.notification.SendNotificationResponse
	6,  // 15: mediaflow.notification.NotificationService.GetDeliveryStatus:output_type -> mediaflow.notification.GetDeliveryStatusResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		EnumInfos:         file_notification_notification_proto_enumTypes,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
