// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: saga/v1/saga.proto

package sagav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "mediaflow/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SagaType int32

const (
	SagaType_SAGA_TYPE_UNSPECIFIED      SagaType = 0
	SagaType_SAGA_TYPE_MEDIA_PROCESSING SagaType = 1
	SagaType_SAGA_TYPE_MEDIA_DELETE     SagaType = 2
)

// Enum value maps for SagaType.
var (
	SagaType_name = map[int32]string{
		0: "SAGA_TYPE_UNSPECIFIED",
		1: "SAGA_TYPE_MEDIA_PROCESSING",
		2: "SAGA_TYPE_MEDIA_DELETE",
	}
	SagaType_value = map[string]int32{
		"SAGA_TYPE_UNSPECIFIED":      0,
		"SAGA_TYPE_MEDIA_PROCESSING": 1,
		"SAGA_TYPE_MEDIA_DELETE":     2,
	}
)

func (x SagaType) Enum() *SagaType {
	p := new(SagaType)
	*p = x
	return p
}

func (x SagaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaType) Descriptor() protoreflect.EnumDescriptor {
	return file_saga_v1_saga_proto_enumTypes[0].Descriptor()
}

func (SagaType) Type() protoreflect.EnumType {
	return &file_saga_v1_saga_proto_enumTypes[0]
}

func (x SagaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaType.Descriptor instead.
func (SagaType) EnumDescriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

type SagaState int32

const (
	SagaState_SAGA_STATE_UNSPECIFIED  SagaState = 0
	SagaState_SAGA_STATE_PENDING      SagaState = 1
	SagaState_SAGA_STATE_RUNNING      SagaState = 2
	SagaState_SAGA_STATE_COMPENSATING SagaState = 3
	SagaState_SAGA_STATE_COMPLETED    SagaState = 4
	SagaState_SAGA_STATE_FAILED       SagaState = 5
)

// Enum value maps for SagaState.
var (
	SagaState_name = map[int32]string{
		0: "SAGA_STATE_UNSPECIFIED",
		1: "SAGA_STATE_PENDING",
		2: "SAGA_STATE_RUNNING",
		3: "SAGA_STATE_COMPENSATING",
		4: "SAGA_STATE_COMPLETED",
		5: "SAGA_STATE_FAILED",
	}
	SagaState_value = map[string]int32{
		"SAGA_STATE_UNSPECIFIED":  0,
		"SAGA_STATE_PENDING":      1,
		"SAGA_STATE_RUNNING":      2,
		"SAGA_STATE_COMPENSATING": 3,
		"SAGA_STATE_COMPLETED":    4,
		"SAGA_STATE_FAILED":       5,
	}
)

func (x SagaState) Enum() *SagaState {
	p := new(SagaState)
	*p = x
	return p
}

func (x SagaState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaState) Descriptor() protoreflect.EnumDescriptor {
	return file_saga_v1_saga_proto_enumTypes[1].Descriptor()
}

func (SagaState) Type() protoreflect.EnumType {
	return &file_saga_v1_saga_proto_enumTypes[1]
}

func (x SagaState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaState.Descriptor instead.
func (SagaState) EnumDescriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_PENDING     StepStatus = 1
	StepStatus_STEP_STATUS_DISPATCHED  StepStatus = 2
	StepStatus_STEP_STATUS_SUCCEEDED   StepStatus = 3
	StepStatus_STEP_STATUS_FAILED      StepStatus = 4
	StepStatus_STEP_STATUS_COMPENSATED StepStatus = 5
	StepStatus_STEP_STATUS_TIMED_OUT   StepStatus = 6
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_PENDING",
		2: "STEP_STATUS_DISPATCHED",
		3: "STEP_STATUS_SUCCEEDED",
		4: "STEP_STATUS_FAILED",
		5: "STEP_STATUS_COMPENSATED",
		6: "STEP_STATUS_TIMED_OUT",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_PENDING":     1,
		"STEP_STATUS_DISPATCHED":  2,
		"STEP_STATUS_SUCCEEDED":   3,
		"STEP_STATUS_FAILED":      4,
		"STEP_STATUS_COMPENSATED": 5,
		"STEP_STATUS_TIMED_OUT":   6,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_saga_v1_saga_proto_enumTypes[2].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_saga_v1_saga_proto_enumTypes[2]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{2}
}

// SagaStep is one node of the orchestration. Each step has a forward
// command and an optional compensation command for rollback.
type SagaStep struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StepNo              int32                  `protobuf:"varint,1,opt,name=step_no,json=stepNo,proto3" json:"step_no,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "transcode"
	Status              StepStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=mediaflow.saga.v1.StepStatus" json:"status,omitempty"`
	Attempt             int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError           string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	DeadlineAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ForwardCommand      string                 `protobuf:"bytes,9,opt,name=forward_command,json=forwardCommand,proto3" json:"forward_command,omitempty"`                 // e.g. "saga.cmd.transcode"
	CompensationCommand string                 `protobuf:"bytes,10,opt,name=compensation_command,json=compensationCommand,proto3" json:"compensation_command,omitempty"` // e.g. "saga.cmd.transcode.cleanup"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SagaStep) Reset() {
	*x = SagaStep{}
	mi := &file_saga_v1_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaStep) ProtoMessage() {}

func (x *SagaStep) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaStep.ProtoReflect.Descriptor instead.
func (*SagaStep) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

func (x *SagaStep) GetStepNo() int32 {
	if x != nil {
		return x.StepNo
	}
	return 0
}

func (x *SagaStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SagaStep) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *SagaStep) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SagaStep) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *SagaStep) GetDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadlineAt
	}
	return nil
}

func (x *SagaStep) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SagaStep) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *SagaStep) GetForwardCommand() string {
	if x != nil {
		return x.ForwardCommand
	}
	return ""
}

func (x *SagaStep) GetCompensationCommand() string {
	if x != nil {
		return x.CompensationCommand
	}
	return ""
}

// Saga is the top-level orchestration aggregate persisted by the
// saga-orchestrator. The full step history is replayable from the steps list.
type Saga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Type          SagaType               `protobuf:"varint,2,opt,name=type,proto3,enum=mediaflow.saga.v1.SagaType" json:"type,omitempty"`
	State         SagaState              `protobuf:"varint,3,opt,name=state,proto3,enum=mediaflow.saga.v1.SagaState" json:"state,omitempty"`
	AggregateId   string                 `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"` // e.g. media_id
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Steps         []*SagaStep            `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // initial input, opaque
	Audit         *v1.Audit              `protobuf:"bytes,8,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Saga) Reset() {
	*x = Saga{}
	mi := &file_saga_v1_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Saga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Saga) ProtoMessage() {}

func (x *Saga) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Saga.ProtoReflect.Descriptor instead.
func (*Saga) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

func (x *Saga) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *Saga) GetType() SagaType {
	if x != nil {
		return x.Type
	}
	return SagaType_SAGA_TYPE_UNSPECIFIED
}

func (x *Saga) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *Saga) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Saga) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Saga) GetSteps() []*SagaStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Saga) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Saga) GetAudit() *v1.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type StartSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SagaType               `protobuf:"varint,1,opt,name=type,proto3,enum=mediaflow.saga.v1.SagaType" json:"type,omitempty"`
	AggregateId   string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSagaRequest) Reset() {
	*x = StartSagaRequest{}
	mi := &file_saga_v1_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSagaRequest) ProtoMessage() {}

func (x *StartSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSagaRequest.ProtoReflect.Descriptor instead.
func (*StartSagaRequest) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{2}
}

func (x *StartSagaRequest) GetType() SagaType {
	if x != nil {
		return x.Type
	}
	return SagaType_SAGA_TYPE_UNSPECIFIED
}

func (x *StartSagaRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *StartSagaRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StartSagaRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSagaRequest) Reset() {
	*x = GetSagaRequest{}
	mi := &file_saga_v1_saga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSagaRequest) ProtoMessage() {}

func (x *GetSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSagaRequest.ProtoReflect.Descriptor instead.
func (*GetSagaRequest) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{3}
}

func (x *GetSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type ListSagasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SagaType               `protobuf:"varint,1,opt,name=type,proto3,enum=mediaflow.saga.v1.SagaType" json:"type,omitempty"`    // optional filter
	State         SagaState              `protobuf:"varint,2,opt,name=state,proto3,enum=mediaflow.saga.v1.SagaState" json:"state,omitempty"` // optional filter
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // optional filter
	Page          *v1.PageRequest        `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasRequest) Reset() {
	*x = ListSagasRequest{}
	mi := &file_saga_v1_saga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasRequest) ProtoMessage() {}

func (x *ListSagasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasRequest.ProtoReflect.Descriptor instead.
func (*ListSagasRequest) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{4}
}

func (x *ListSagasRequest) GetType() SagaType {
	if x != nil {
		return x.Type
	}
	return SagaType_SAGA_TYPE_UNSPECIFIED
}

func (x *ListSagasRequest) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *ListSagasRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSagasRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSagasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sagas         []*Saga                `protobuf:"bytes,1,rep,name=sagas,proto3" json:"sagas,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasResponse) Reset() {
	*x = ListSagasResponse{}
	mi := &file_saga_v1_saga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasResponse) ProtoMessage() {}

func (x *ListSagasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasResponse.ProtoReflect.Descriptor instead.
func (*ListSagasResponse) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{5}
}

func (x *ListSagasResponse) GetSagas() []*Saga {
	if x != nil {
		return x.Sagas
	}
	return nil
}

func (x *ListSagasResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type RetrySagaStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	StepNo        int32                  `protobuf:"varint,2,opt,name=step_no,json=stepNo,proto3" json:"step_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySagaStepRequest) Reset() {
	*x = RetrySagaStepRequest{}
	mi := &file_saga_v1_saga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySagaStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySagaStepRequest) ProtoMessage() {}

func (x *RetrySagaStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySagaStepRequest.ProtoReflect.Descriptor instead.
func (*RetrySagaStepRequest) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{6}
}

func (x *RetrySagaStepRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *RetrySagaStepRequest) GetStepNo() int32 {
	if x != nil {
		return x.StepNo
	}
	return 0
}

type RetrySagaStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *Saga                  `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySagaStepResponse) Reset() {
	*x = RetrySagaStepResponse{}
	mi := &file_saga_v1_saga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySagaStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySagaStepResponse) ProtoMessage() {}

func (x *RetrySagaStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySagaStepResponse.ProtoReflect.Descriptor instead.
func (*RetrySagaStepResponse) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{7}
}

func (x *RetrySagaStepResponse) GetSaga() *Saga {
	if x != nil {
		return x.Saga
	}
	return nil
}

// SagaCommand is the envelope the orchestrator publishes to step-specific
// command topics (saga.cmd.transcode.v1, saga.cmd.thumbnail.v1, ...).
// The receiving service uses command_id as its idempotency key.
type SagaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // UUID, dedup key
	SagaId        string                 `protobuf:"bytes,2,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	StepNo        int32                  `protobuf:"varint,3,opt,name=step_no,json=stepNo,proto3" json:"step_no,omitempty"`
	CommandType   string                 `protobuf:"bytes,4,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // e.g. "TranscodeMedia"
	AggregateId   string                 `protobuf:"bytes,5,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"` // e.g. media_id
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                            // service-specific message
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	DeadlineAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaCommand) Reset() {
	*x = SagaCommand{}
	mi := &file_saga_v1_saga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaCommand) ProtoMessage() {}

func (x *SagaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaCommand.ProtoReflect.Descriptor instead.
func (*SagaCommand) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{8}
}

func (x *SagaCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SagaCommand) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *SagaCommand) GetStepNo() int32 {
	if x != nil {
		return x.StepNo
	}
	return 0
}

func (x *SagaCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *SagaCommand) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *SagaCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SagaCommand) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *SagaCommand) GetDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadlineAt
	}
	return nil
}

// SagaReply is the envelope every worker publishes back to saga.reply.v1
// when a command finishes. Partitioned by saga_id so the same orchestrator
// instance handles all replies for a saga.
type SagaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // matches the command
	SagaId        string                 `protobuf:"bytes,2,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	StepNo        int32                  `protobuf:"varint,3,opt,name=step_no,json=stepNo,proto3" json:"step_no,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         *v1.Error              `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`     // set if !success
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // service-specific result
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaReply) Reset() {
	*x = SagaReply{}
	mi := &file_saga_v1_saga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaReply) ProtoMessage() {}

func (x *SagaReply) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_saga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaReply.ProtoReflect.Descriptor instead.
func (*SagaReply) Descriptor() ([]byte, []int) {
	return file_saga_v1_saga_proto_rawDescGZIP(), []int{9}
}

func (x *SagaReply) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SagaReply) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *SagaReply) GetStepNo() int32 {
	if x != nil {
		return x.StepNo
	}
	return 0
}

func (x *SagaReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SagaReply) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SagaReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SagaReply) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_saga_v1_saga_proto protoreflect.FileDescriptor

const file_saga_v1_saga_proto_rawDesc = "" +
	"\n" +
	"\x12saga/v1/saga.proto\x12\x11mediaflow.saga.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xb8\x03\n" +
	"\bSagaStep\x12\x17\n" +
	"\astep_no\x18\x01 \x01(\x05R\x06stepNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.mediaflow.saga.v1.StepStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12;\n" +
	"\vdeadline_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deadlineAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12'\n" +
	"\x0fforward_command\x18\t \x01(\tR\x0eforwardCommand\x121\n" +
	"\x14compensation_command\x18\n" +
	" \x01(\tR\x13compensationCommand\"\xcd\x02\n" +
	"\x04Saga\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.mediaflow.saga.v1.SagaTypeR\x04type\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.mediaflow.saga.v1.SagaStateR\x05state\x12!\n" +
	"\faggregate_id\x18\x04 \x01(\tR\vaggregateId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x121\n" +
	"\x05steps\x18\x06 \x03(\v2\x1b.mediaflow.saga.v1.SagaStepR\x05steps\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x120\n" +
	"\x05audit\x18\b \x01(\v2\x1a.mediaflow.common.v1.AuditR\x05audit\"\xa7\x01\n" +
	"\x10StartSagaRequest\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.mediaflow.saga.v1.SagaTypeR\x04type\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\")\n" +
	"\x0eGetSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\"\xc6\x01\n" +
	"\x10ListSagasRequest\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.mediaflow.saga.v1.SagaTypeR\x04type\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.mediaflow.saga.v1.SagaStateR\x05state\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\x04page\x18\x04 \x01(\v2 .mediaflow.common.v1.PageRequestR\x04page\"y\n" +
	"\x11ListSagasResponse\x12-\n" +
	"\x05sagas\x18\x01 \x03(\v2\x17.mediaflow.saga.v1.SagaR\x05sagas\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.mediaflow.common.v1.PageResponseR\x04page\"H\n" +
	"\x14RetrySagaStepRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\astep_no\x18\x02 \x01(\x05R\x06stepNo\"D\n" +
	"\x15RetrySagaStepResponse\x12+\n" +
	"\x04saga\x18\x01 \x01(\v2\x17.mediaflow.saga.v1.SagaR\x04saga\"\xb4\x02\n" +
	"\vSagaCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\asaga_id\x18\x02 \x01(\tR\x06sagaId\x12\x17\n" +
	"\astep_no\x18\x03 \x01(\x05R\x06stepNo\x12!\n" +
	"\fcommand_type\x18\x04 \x01(\tR\vcommandType\x12!\n" +
	"\faggregate_id\x18\x05 \x01(\tR\vaggregateId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12;\n" +
	"\vdeadline_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deadlineAt\"\xff\x01\n" +
	"\tSagaReply\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\asaga_id\x18\x02 \x01(\tR\x06sagaId\x12\x17\n" +
	"\astep_no\x18\x03 \x01(\x05R\x06stepNo\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.mediaflow.common.v1.ErrorR\x05error\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*a\n" +
	"\bSagaType\x12\x19\n" +
	"\x15SAGA_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSAGA_TYPE_MEDIA_PROCESSING\x10\x01\x12\x1a\n" +
	"\x16SAGA_TYPE_MEDIA_DELETE\x10\x02*\xa5\x01\n" +
	"\tSagaState\x12\x1a\n" +
	"\x16SAGA_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SAGA_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12SAGA_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17SAGA_STATE_COMPENSATING\x10\x03\x12\x18\n" +
	"\x14SAGA_STATE_COMPLETED\x10\x04\x12\x15\n" +
	"\x11SAGA_STATE_FAILED\x10\x05*\xc9\x01\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STEP_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16STEP_STATUS_DISPATCHED\x10\x02\x12\x19\n" +
	"\x15STEP_STATUS_SUCCEEDED\x10\x03\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17STEP_STATUS_COMPENSATED\x10\x05\x12\x19\n" +
	"\x15STEP_STATUS_TIMED_OUT\x10\x062\xdb\x02\n" +
	"\vSagaService\x12I\n" +
	"\tStartSaga\x12#.mediaflow.saga.v1.StartSagaRequest\x1a\x17.mediaflow.saga.v1.Saga\x12E\n" +
	"\aGetSaga\x12!.mediaflow.saga.v1.GetSagaRequest\x1a\x17.mediaflow.saga.v1.Saga\x12V\n" +
	"\tListSagas\x12#.mediaflow.saga.v1.ListSagasRequest\x1a$.mediaflow.saga.v1.ListSagasResponse\x12b\n" +
	"\rRetrySagaStep\x12'.mediaflow.saga.v1.RetrySagaStepRequest\x1a(.mediaflow.saga.v1.RetrySagaStepResponseB Z\x1emediaflow/proto/saga/v1;sagav1b\x06proto3"

var (
	file_saga_v1_saga_proto_rawDescOnce sync.Once
	file_saga_v1_saga_proto_rawDescData []byte
)

func file_saga_v1_saga_proto_rawDescGZIP() []byte {
	file_saga_v1_saga_proto_rawDescOnce.Do(func() {
		file_saga_v1_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saga_v1_saga_proto_rawDesc), len(file_saga_v1_saga_proto_rawDesc)))
	})
	return file_saga_v1_saga_proto_rawDescData
}

var file_saga_v1_saga_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_saga_v1_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_saga_v1_saga_proto_goTypes = []any{
	(SagaType)(0),                 // 0: mediaflow.saga.v1.SagaType
	(SagaState)(0),                // 1: mediaflow.saga.v1.SagaState
	(StepStatus)(0),               // 2: mediaflow.saga.v1.StepStatus
	(*SagaStep)(nil),              // 3: mediaflow.saga.v1.SagaStep
	(*Saga)(nil),                  // 4: mediaflow.saga.v1.Saga
	(*StartSagaRequest)(nil),      // 5: mediaflow.saga.v1.StartSagaRequest
	(*GetSagaRequest)(nil),        // 6: mediaflow.saga.v1.GetSagaRequest
	(*ListSagasRequest)(nil),      // 7: mediaflow.saga.v1.ListSagasRequest
	(*ListSagasResponse)(nil),     // 8: mediaflow.saga.v1.ListSagasResponse
	(*RetrySagaStepRequest)(nil),  // 9: mediaflow.saga.v1.RetrySagaStepRequest
	(*RetrySagaStepResponse)(nil), // 10: mediaflow.saga.v1.RetrySagaStepResponse
	(*SagaCommand)(nil),           // 11: mediaflow.saga.v1.SagaCommand
	(*SagaReply)(nil),             // 12: mediaflow.saga.v1.SagaReply
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*v1.Audit)(nil),              // 14: mediaflow.common.v1.Audit
	(*v1.PageRequest)(nil),        // 15: mediaflow.common.v1.PageRequest
	(*v1.PageResponse)(nil),       // 16: mediaflow.common.v1.PageResponse
	(*v1.Error)(nil),              // 17: mediaflow.common.v1.Error
}
var file_saga_v1_saga_proto_depIdxs = []int32{
	2,  // 0: mediaflow.saga.v1.SagaStep.status:type_name -> mediaflow.saga.v1.StepStatus
	13, // 1: mediaflow.saga.v1.SagaStep.deadline_at:type_name -> google.protobuf.Timestamp
	13, // 2: mediaflow.saga.v1.SagaStep.started_at:type_name -> google.protobuf.Timestamp
	13, // 3: mediaflow.saga.v1.SagaStep.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 4: mediaflow.saga.v1.Saga.type:type_name -> mediaflow.saga.v1.SagaType
	1,  // 5: mediaflow.saga.v1.Saga.state:type_name -> mediaflow.saga.v1.SagaState
	3,  // 6: mediaflow.saga.v1.Saga.steps:type_name -> mediaflow.saga.v1.SagaStep
	14, // 7: mediaflow.saga.v1.Saga.audit:type_name -> mediaflow.common.v1.Audit
	0,  // 8: mediaflow.saga.v1.StartSagaRequest.type:type_name -> mediaflow.saga.v1.SagaType
	0,  // 9: mediaflow.saga.v1.ListSagasRequest.type:type_name -> mediaflow.saga.v1.SagaType
	1,  // 10: mediaflow.saga.v1.ListSagasRequest.state:type_name -> mediaflow.saga.v1.SagaState
	15, // 11: mediaflow.saga.v1.ListSagasRequest.page:type_name -> mediaflow.common.v1.PageRequest
	4,  // 12: mediaflow.saga.v1.ListSagasResponse.sagas:type_name -> mediaflow.saga.v1.Saga
	16, // 13: mediaflow.saga.v1.ListSagasResponse.page:type_name -> mediaflow.common.v1.PageResponse
	4,  // 14: mediaflow.saga.v1.RetrySagaStepResponse.saga:type_name -> mediaflow.saga.v1.Saga
	13, // 15: mediaflow.saga.v1.SagaCommand.issued_at:type_name -> google.protobuf.Timestamp
	13, // 16: mediaflow.saga.v1.SagaCommand.deadline_at:type_name -> google.protobuf.Timestamp
	17, // 17: mediaflow.saga.v1.SagaReply.error:type_name -> mediaflow.common.v1.Error
	13, // 18: mediaflow.saga.v1.SagaReply.finished_at:type_name -> google.protobuf.Timestamp
	5,  // 19: mediaflow.saga.v1.SagaService.StartSaga:input_type -> mediaflow.saga.v1.StartSagaRequest
	6,  // 20: mediaflow.saga.v1.SagaService.GetSaga:input_type -> mediaflow.saga.v1.GetSagaRequest
	7,  // 21: mediaflow.saga.v1.SagaService.ListSagas:input_type -> mediaflow.saga.v1.ListSagasRequest
	9,  // 22: mediaflow.saga.v1.SagaService.RetrySagaStep:input_type -> mediaflow.saga.v1.RetrySagaStepRequest
	4,  // 23: mediaflow.saga.v1.SagaService.StartSaga:output_type -> mediaflow.saga.v1.Saga
	4,  // 24: mediaflow.saga.v1.SagaService.GetSaga:output_type -> mediaflow.saga.v1.Saga
	8,  // 25: mediaflow.saga.v1.SagaService.ListSagas:output_type -> mediaflow.saga.v1.ListSagasResponse
	10, // 26: mediaflow.saga.v1.SagaService.RetrySagaStep:output_type -> mediaflow.saga.v1.RetrySagaStepResponse
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_saga_v1_saga_proto_init() }
func file_saga_v1_saga_proto_init() {
	if File_saga_v1_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saga_v1_saga_proto_rawDesc), len(file_saga_v1_saga_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saga_v1_saga_proto_goTypes,
		DependencyIndexes: file_saga_v1_saga_proto_depIdxs,
		EnumInfos:         file_saga_v1_saga_proto_enumTypes,
		MessageInfos:      file_saga_v1_saga_proto_msgTypes,
	}.Build()
	File_saga_v1_saga_proto = out.File
	file_saga_v1_saga_proto_goTypes = nil
	file_saga_v1_saga_proto_depIdxs = nil
}
