// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.23.3
// source: saga/v1/saga.proto

package sagav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaService_StartSaga_FullMethodName     = "/mediaflow.saga.v1.SagaService/StartSaga"
	SagaService_GetSaga_FullMethodName       = "/mediaflow.saga.v1.SagaService/GetSaga"
	SagaService_ListSagas_FullMethodName     = "/mediaflow.saga.v1.SagaService/ListSagas"
	SagaService_RetrySagaStep_FullMethodName = "/mediaflow.saga.v1.SagaService/RetrySagaStep"
)

// SagaServiceClient is the client API for SagaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaServiceClient interface {
	StartSaga(ctx context.Context, in *StartSagaRequest, opts ...grpc.CallOption) (*Saga, error)
	GetSaga(ctx context.Context, in *GetSagaRequest, opts ...grpc.CallOption) (*Saga, error)
	ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error)
	RetrySagaStep(ctx context.Context, in *RetrySagaStepRequest, opts ...grpc.CallOption) (*RetrySagaStepResponse, error)
}

type sagaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaServiceClient(cc grpc.ClientConnInterface) SagaServiceClient {
	return &sagaServiceClient{cc}
}

func (c *sagaServiceClient) StartSaga(ctx context.Context, in *StartSagaRequest, opts ...grpc.CallOption) (*Saga, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Saga)
	err := c.cc.Invoke(ctx, SagaService_StartSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) GetSaga(ctx context.Context, in *GetSagaRequest, opts ...grpc.CallOption) (*Saga, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Saga)
	err := c.cc.Invoke(ctx, SagaService_GetSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSagasResponse)
	err := c.cc.Invoke(ctx, SagaService_ListSagas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) RetrySagaStep(ctx context.Context, in *RetrySagaStepRequest, opts ...grpc.CallOption) (*RetrySagaStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrySagaStepResponse)
	err := c.cc.Invoke(ctx, SagaService_RetrySagaStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaServiceServer is the server API for SagaService service.
// All implementations must embed UnimplementedSagaServiceServer
// for forward compatibility.
type SagaServiceServer interface {
	StartSaga(context.Context, *StartSagaRequest) (*Saga, error)
	GetSaga(context.Context, *GetSagaRequest) (*Saga, error)
	ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error)
	RetrySagaStep(context.Context, *RetrySagaStepRequest) (*RetrySagaStepResponse, error)
	mustEmbedUnimplementedSagaServiceServer()
}

// UnimplementedSagaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaServiceServer struct{}

func (UnimplementedSagaServiceServer) StartSaga(context.Context, *StartSagaRequest) (*Saga, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSaga not implemented")
}
func (UnimplementedSagaServiceServer) GetSaga(context.Context, *GetSagaRequest) (*Saga, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSaga not implemented")
}
func (UnimplementedSagaServiceServer) ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSagas not implemented")
}
func (UnimplementedSagaServiceServer) RetrySagaStep(context.Context, *RetrySagaStepRequest) (*RetrySagaStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrySagaStep not implemented")
}
func (UnimplementedSagaServiceServer) mustEmbedUnimplementedSagaServiceServer() {}
func (UnimplementedSagaServiceServer) testEmbeddedByValue()                     {}

// UnsafeSagaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaServiceServer will
// result in compilation errors.
type UnsafeSagaServiceServer interface {
	mustEmbedUnimplementedSagaServiceServer()
}

func RegisterSagaServiceServer(s grpc.ServiceRegistrar, srv SagaServiceServer) {
	// If the following call panics, it indicates UnimplementedSagaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaService_ServiceDesc, srv)
}

func _SagaService_StartSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).StartSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_StartSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).StartSaga(ctx, req.(*StartSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_GetSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).GetSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_GetSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).GetSaga(ctx, req.(*GetSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_ListSagas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSagasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).ListSagas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_ListSagas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).ListSagas(ctx, req.(*ListSagasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_RetrySagaStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrySagaStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).RetrySagaStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_RetrySagaStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).RetrySagaStep(ctx, req.(*RetrySagaStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaService_ServiceDesc is the grpc.ServiceDesc for SagaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediaflow.saga.v1.SagaService",
	HandlerType: (*SagaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSaga",
			Handler:    _SagaService_StartSaga_Handler,
		},
		{
			MethodName: "GetSaga",
			Handler:    _SagaService_GetSaga_Handler,
		},
		{
			MethodName: "ListSagas",
			Handler:    _SagaService_ListSagas_Handler,
		},
		{
			MethodName: "RetrySagaStep",
			Handler:    _SagaService_RetrySagaStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saga/v1/saga.proto",
}
