// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: metadata/v1/metadata.proto

package metadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "mediaflow/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	FrameRate     float64                `protobuf:"fixed64,4,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,5,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStream) Reset() {
	*x = VideoStream{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStream) ProtoMessage() {}

func (x *VideoStream) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStream.ProtoReflect.Descriptor instead.
func (*VideoStream) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *VideoStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *VideoStream) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoStream) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoStream) GetFrameRate() float64 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *VideoStream) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

type AudioStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`
	Channels      int32                  `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,4,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"` // BCP-47, optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioStream) Reset() {
	*x = AudioStream{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStream) ProtoMessage() {}

func (x *AudioStream) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStream.ProtoReflect.Descriptor instead.
func (*AudioStream) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *AudioStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioStream) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioStream) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioStream) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *AudioStream) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Metadata is the extracted technical description of a media asset. It is
// owned by metadata-service and projected into the read model by
// media-query-service.
type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaId         string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Container       string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"` // e.g. "mp4", "mov"
	DurationSeconds float64                `protobuf:"fixed64,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	VideoStreams    []*VideoStream         `protobuf:"bytes,5,rep,name=video_streams,json=videoStreams,proto3" json:"video_streams,omitempty"`
	AudioStreams    []*AudioStream         `protobuf:"bytes,6,rep,name=audio_streams,json=audioStreams,proto3" json:"audio_streams,omitempty"`
	ChecksumSha256  string                 `protobuf:"bytes,7,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	ExtractedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=extracted_at,json=extractedAt,proto3" json:"extracted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Metadata) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *Metadata) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Metadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Metadata) GetVideoStreams() []*VideoStream {
	if x != nil {
		return x.VideoStreams
	}
	return nil
}

func (x *Metadata) GetAudioStreams() []*AudioStream {
	if x != nil {
		return x.AudioStreams
	}
	return nil
}

func (x *Metadata) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *Metadata) GetExtractedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExtractedAt
	}
	return nil
}

type ExtractMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SourceS3Key   string                 `protobuf:"bytes,2,opt,name=source_s3_key,json=sourceS3Key,proto3" json:"source_s3_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractMetadataRequest) Reset() {
	*x = ExtractMetadataRequest{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractMetadataRequest) ProtoMessage() {}

func (x *ExtractMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractMetadataRequest.ProtoReflect.Descriptor instead.
func (*ExtractMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractMetadataRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ExtractMetadataRequest) GetSourceS3Key() string {
	if x != nil {
		return x.SourceS3Key
	}
	return ""
}

type ExtractMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractMetadataResponse) Reset() {
	*x = ExtractMetadataResponse{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractMetadataResponse) ProtoMessage() {}

func (x *ExtractMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractMetadataResponse.ProtoReflect.Descriptor instead.
func (*ExtractMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractMetadataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetadataRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type MetadataExtracted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExtractedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=extracted_at,json=extractedAt,proto3" json:"extracted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataExtracted) Reset() {
	*x = MetadataExtracted{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataExtracted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExtracted) ProtoMessage() {}

func (x *MetadataExtracted) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExtracted.ProtoReflect.Descriptor instead.
func (*MetadataExtracted) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataExtracted) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MetadataExtracted) GetExtractedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExtractedAt
	}
	return nil
}

type MetadataExtractionFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Error         *v1.Error              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataExtractionFailed) Reset() {
	*x = MetadataExtractionFailed{}
	mi := &file_metadata_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataExtractionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExtractionFailed) ProtoMessage() {}

func (x *MetadataExtractionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExtractionFailed.ProtoReflect.Descriptor instead.
func (*MetadataExtractionFailed) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataExtractionFailed) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MetadataExtractionFailed) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MetadataExtractionFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_metadata_v1_metadata_proto protoreflect.FileDescriptor

const file_metadata_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1ametadata/v1/metadata.proto\x12\x15mediaflow.metadata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\x93\x01\n" +
	"\vVideoStream\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x04 \x01(\x01R\tframeRate\x12!\n" +
	"\fbitrate_kbps\x18\x05 \x01(\x05R\vbitrateKbps\"\x9f\x01\n" +
	"\vAudioStream\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\x05R\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12!\n" +
	"\fbitrate_kbps\x18\x04 \x01(\x05R\vbitrateKbps\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\x87\x03\n" +
	"\bMetadata\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x01R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12G\n" +
	"\rvideo_streams\x18\x05 \x03(\v2\".mediaflow.metadata.v1.VideoStreamR\fvideoStreams\x12G\n" +
	"\raudio_streams\x18\x06 \x03(\v2\".mediaflow.metadata.v1.AudioStreamR\faudioStreams\x12'\n" +
	"\x0fchecksum_sha256\x18\a \x01(\tR\x0echecksumSha256\x12=\n" +
	"\fextracted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vextractedAt\"W\n" +
	"\x16ExtractMetadataRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\"\n" +
	"\rsource_s3_key\x18\x02 \x01(\tR\vsourceS3Key\"V\n" +
	"\x17ExtractMetadataResponse\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.mediaflow.metadata.v1.MetadataR\bmetadata\"/\n" +
	"\x12GetMetadataRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x8f\x01\n" +
	"\x11MetadataExtracted\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.mediaflow.metadata.v1.MetadataR\bmetadata\x12=\n" +
	"\fextracted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vextractedAt\"\x81\x01\n" +
	"\x18MetadataExtractionFailed\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x120\n" +
	"\x05error\x18\x02 \x01(\v2\x1a.mediaflow.common.v1.ErrorR\x05error\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt2\xde\x01\n" +
	"\x0fMetadataService\x12p\n" +
	"\x0fExtractMetadata\x12-.mediaflow.metadata.v1.ExtractMetadataRequest\x1a..mediaflow.metadata.v1.ExtractMetadataResponse\x12Y\n" +
	"\vGetMetadata\x12).mediaflow.metadata.v1.GetMetadataRequest\x1a\x1f.mediaflow.metadata.v1.MetadataB(Z&mediaflow/proto/metadata/v1;metadatav1b\x06proto3"

var (
	file_metadata_v1_metadata_proto_rawDescOnce sync.Once
	file_metadata_v1_metadata_proto_rawDescData []byte
)

func file_metadata_v1_metadata_proto_rawDescGZIP() []byte {
	file_metadata_v1_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_v1_metadata_proto_rawDesc), len(file_metadata_v1_metadata_proto_rawDesc)))
	})
	return file_metadata_v1_metadata_proto_rawDescData
}

var file_metadata_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_metadata_v1_metadata_proto_goTypes = []any{
	(*VideoStream)(nil),              // 0: mediaflow.metadata.v1.VideoStream
	(*AudioStream)(nil),              // 1: mediaflow.metadata.v1.AudioStream
	(*Metadata)(nil),                 // 2: mediaflow.metadata.v1.Metadata
	(*ExtractMetadataRequest)(nil),   // 3: mediaflow.metadata.v1.ExtractMetadataRequest
	(*ExtractMetadataResponse)(nil),  // 4: mediaflow.metadata.v1.ExtractMetadataResponse
	(*GetMetadataRequest)(nil),       // 5: mediaflow.metadata.v1.GetMetadataRequest
	(*MetadataExtracted)(nil),        // 6: mediaflow.metadata.v1.MetadataExtracted
	(*MetadataExtractionFailed)(nil), // 7: mediaflow.metadata.v1.MetadataExtractionFailed
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*v1.Error)(nil),                 // 9: mediaflow.common.v1.Error
}
var file_metadata_v1_metadata_proto_depIdxs = []int32{
	0, // 0: mediaflow.metadata.v1.Metadata.video_streams:type_name -> mediaflow.metadata.v1.VideoStream
	1, // 1: mediaflow.metadata.v1.Metadata.audio_streams:type_name -> mediaflow.metadata.v1.AudioStream
	8, // 2: mediaflow.metadata.v1.Metadata.extracted_at:type_name -> google.protobuf.Timestamp
	2, // 3: mediaflow.metadata.v1.ExtractMetadataResponse.metadata:type_name -> mediaflow.metadata.v1.Metadata
	2, // 4: mediaflow.metadata.v1.MetadataExtracted.metadata:type_name -> mediaflow.metadata.v1.Metadata
	8, // 5: mediaflow.metadata.v1.MetadataExtracted.extracted_at:type_name -> google.protobuf.Timestamp
	9, // 6: mediaflow.metadata.v1.MetadataExtractionFailed.error:type_name -> mediaflow.common.v1.Error
	3, // 7: mediaflow.metadata.v1.MetadataService.ExtractMetadata:input_type -> mediaflow.metadata.v1.ExtractMetadataRequest
	5, // 8: mediaflow.metadata.v1.MetadataService.GetMetadata:input_type -> mediaflow.metadata.v1.GetMetadataRequest
	4, // 9: mediaflow.metadata.v1.MetadataService.ExtractMetadata:output_type -> mediaflow.metadata.v1.ExtractMetadataResponse
	2, // 10: mediaflow.metadata.v1.MetadataService.GetMetadata:output_type -> mediaflow.metadata.v1.Metadata
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_metadata_v1_metadata_proto_init() }
func file_metadata_v1_metadata_proto_init() {
	if File_metadata_v1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_v1_metadata_proto_rawDesc), len(file_metadata_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_v1_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_v1_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_v1_metadata_proto_msgTypes,
	}.Build()
	File_metadata_v1_metadata_proto = out.File
	file_metadata_v1_metadata_proto_goTypes = nil
	file_metadata_v1_metadata_proto_depIdxs = nil
}
