// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: thumbnail/thumbnail.proto

package thumbnail

import (
	common "github.com/tolgafiratoglu/mediaflow/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Strategy controls how thumbnails are sampled from the source media.
type Strategy int32

const (
	Strategy_STRATEGY_UNSPECIFIED  Strategy = 0
	Strategy_STRATEGY_FIRST_FRAME  Strategy = 1
	Strategy_STRATEGY_MIDPOINT     Strategy = 2
	Strategy_STRATEGY_EVERY_N_SECS Strategy = 3
	Strategy_STRATEGY_SCENE_CHANGE Strategy = 4
)

// Enum value maps for Strategy.
var (
	Strategy_name = map[int32]string{
		0: "STRATEGY_UNSPECIFIED",
		1: "STRATEGY_FIRST_FRAME",
		2: "STRATEGY_MIDPOINT",
		3: "STRATEGY_EVERY_N_SECS",
		4: "STRATEGY_SCENE_CHANGE",
	}
	Strategy_value = map[string]int32{
		"STRATEGY_UNSPECIFIED":  0,
		"STRATEGY_FIRST_FRAME":  1,
		"STRATEGY_MIDPOINT":     2,
		"STRATEGY_EVERY_N_SECS": 3,
		"STRATEGY_SCENE_CHANGE": 4,
	}
)

func (x Strategy) Enum() *Strategy {
	p := new(Strategy)
	*p = x
	return p
}

func (x Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_thumbnail_thumbnail_proto_enumTypes[0].Descriptor()
}

func (Strategy) Type() protoreflect.EnumType {
	return &file_thumbnail_thumbnail_proto_enumTypes[0]
}

func (x Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strategy.Descriptor instead.
func (Strategy) EnumDescriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{0}
}

type Thumbnail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	S3Bucket         string                 `protobuf:"bytes,1,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Key            string                 `protobuf:"bytes,2,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Width            int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	TimestampSeconds float64                `protobuf:"fixed64,5,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"` // offset within the source where it was sampled
	SizeBytes        int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Thumbnail) Reset() {
	*x = Thumbnail{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thumbnail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumbnail) ProtoMessage() {}

func (x *Thumbnail) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumbnail.ProtoReflect.Descriptor instead.
func (*Thumbnail) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{0}
}

func (x *Thumbnail) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *Thumbnail) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Thumbnail) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Thumbnail) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Thumbnail) GetTimestampSeconds() float64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *Thumbnail) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,3,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Strategy      Strategy               `protobuf:"varint,4,opt,name=strategy,proto3,enum=mediaflow.thumbnail.Strategy" json:"strategy,omitempty"`
	Status        common.Status          `protobuf:"varint,5,opt,name=status,proto3,enum=mediaflow.common.Status" json:"status,omitempty"`
	Thumbnails    []*Thumbnail           `protobuf:"bytes,6,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Attempt       int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Job) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *Job) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_STRATEGY_UNSPECIFIED
}

func (x *Job) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *Job) GetThumbnails() []*Thumbnail {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type GenerateThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SourceS3Key   string                 `protobuf:"bytes,2,opt,name=source_s3_key,json=sourceS3Key,proto3" json:"source_s3_key,omitempty"`
	Strategy      Strategy               `protobuf:"varint,3,opt,name=strategy,proto3,enum=mediaflow.thumbnail.Strategy" json:"strategy,omitempty"`
	EveryNSecs    int32                  `protobuf:"varint,4,opt,name=every_n_secs,json=everyNSecs,proto3" json:"every_n_secs,omitempty"` // used only with STRATEGY_EVERY_N_SECS
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`                               // 0 means service default
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`                             // 0 means service default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateThumbnailRequest) Reset() {
	*x = GenerateThumbnailRequest{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateThumbnailRequest) ProtoMessage() {}

func (x *GenerateThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GenerateThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateThumbnailRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GenerateThumbnailRequest) GetSourceS3Key() string {
	if x != nil {
		return x.SourceS3Key
	}
	return ""
}

func (x *GenerateThumbnailRequest) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_STRATEGY_UNSPECIFIED
}

func (x *GenerateThumbnailRequest) GetEveryNSecs() int32 {
	if x != nil {
		return x.EveryNSecs
	}
	return 0
}

func (x *GenerateThumbnailRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GenerateThumbnailRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GenerateThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateThumbnailResponse) Reset() {
	*x = GenerateThumbnailResponse{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateThumbnailResponse) ProtoMessage() {}

func (x *GenerateThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateThumbnailResponse.ProtoReflect.Descriptor instead.
func (*GenerateThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateThumbnailResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ThumbnailGenerated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Thumbnails    []*Thumbnail           `protobuf:"bytes,2,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailGenerated) Reset() {
	*x = ThumbnailGenerated{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailGenerated) ProtoMessage() {}

func (x *ThumbnailGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailGenerated.ProtoReflect.Descriptor instead.
func (*ThumbnailGenerated) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{5}
}

func (x *ThumbnailGenerated) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ThumbnailGenerated) GetThumbnails() []*Thumbnail {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

func (x *ThumbnailGenerated) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ThumbnailFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailFailed) Reset() {
	*x = ThumbnailFailed{}
	mi := &file_thumbnail_thumbnail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailFailed) ProtoMessage() {}

func (x *ThumbnailFailed) ProtoReflect() protoreflect.Message {
	mi := &file_thumbnail_thumbnail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailFailed.ProtoReflect.Descriptor instead.
func (*ThumbnailFailed) Descriptor() ([]byte, []int) {
	return file_thumbnail_thumbnail_proto_rawDescGZIP(), []int{6}
}

func (x *ThumbnailFailed) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ThumbnailFailed) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ThumbnailFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_thumbnail_thumbnail_proto protoreflect.FileDescriptor

const file_thumbnail_thumbnail_proto_rawDesc = "" +
	"\n" +
	"\x19thumbnail/thumbnail.proto\x12\x13mediaflow.thumbnail\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xb9\x01\n" +
	"\tThumbnail\x12\x1b\n" +
	"\ts3_bucket\x18\x01 \x01(\tR\bs3Bucket\x12\x15\n" +
	"\x06s3_key\x18\x02 \x01(\tR\x05s3Key\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12+\n" +
	"\x11timestamp_seconds\x18\x05 \x01(\x01R\x10timestampSeconds\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\"\xae\x03\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x17\n" +
	"\asaga_id\x18\x03 \x01(\tR\x06sagaId\x129\n" +
	"\bstrategy\x18\x04 \x01(\x0e2\x1d.mediaflow.thumbnail.StrategyR\bstrategy\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.mediaflow.common.StatusR\x06status\x12>\n" +
	"\n" +
	"thumbnails\x18\x06 \x03(\v2\x1e.mediaflow.thumbnail.ThumbnailR\n" +
	"thumbnails\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xe4\x01\n" +
	"\x18GenerateThumbnailRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\"\n" +
	"\rsource_s3_key\x18\x02 \x01(\tR\vsourceS3Key\x129\n" +
	"\bstrategy\x18\x03 \x01(\x0e2\x1d.mediaflow.thumbnail.StrategyR\bstrategy\x12 \n" +
	"\fevery_n_secs\x18\x04 \x01(\x05R\n" +
	"everyNSecs\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\"G\n" +
	"\x19GenerateThumbnailResponse\x12*\n" +
	"\x03job\x18\x01 \x01(\v2\x18.mediaflow.thumbnail.JobR\x03job\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xae\x01\n" +
	"\x12ThumbnailGenerated\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12>\n" +
	"\n" +
	"thumbnails\x18\x02 \x03(\v2\x1e.mediaflow.thumbnail.ThumbnailR\n" +
	"thumbnails\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"u\n" +
	"\x0fThumbnailFailed\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.mediaflow.common.ErrorR\x05error\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt*\x8b\x01\n" +
	"\bStrategy\x12\x18\n" +
	"\x14STRATEGY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STRATEGY_FIRST_FRAME\x10\x01\x12\x15\n" +
	"\x11STRATEGY_MIDPOINT\x10\x02\x12\x19\n" +
	"\x15STRATEGY_EVERY_N_SECS\x10\x03\x12\x19\n" +
	"\x15STRATEGY_SCENE_CHANGE\x10\x042\xce\x01\n" +
	"\x10ThumbnailService\x12r\n" +
	"\x11GenerateThumbnail\x12-.mediaflow.thumbnail.GenerateThumbnailRequest\x1a..mediaflow.thumbnail.GenerateThumbnailResponse\x12F\n" +
	"\x06GetJob\x12\".mediaflow.thumbnail.GetJobRequest\x1a\x18.mediaflow.thumbnail.JobB?Z=github.com/tolgafiratoglu/mediaflow/proto/thumbnail;thumbnailb\x06proto3"

var (
	file_thumbnail_thumbnail_proto_rawDescOnce sync.Once
	file_thumbnail_thumbnail_proto_rawDescData []byte
)

func file_thumbnail_thumbnail_proto_rawDescGZIP() []byte {
	file_thumbnail_thumbnail_proto_rawDescOnce.Do(func() {
		file_thumbnail_thumbnail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thumbnail_thumbnail_proto_rawDesc), len(file_thumbnail_thumbnail_proto_rawDesc)))
	})
	return file_thumbnail_thumbnail_proto_rawDescData
}

var file_thumbnail_thumbnail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_thumbnail_thumbnail_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_thumbnail_thumbnail_proto_goTypes = []any{
	(Strategy)(0),                     // 0: mediaflow.thumbnail.Strategy
	(*Thumbnail)(nil),                 // 1: mediaflow.thumbnail.Thumbnail
	(*Job)(nil),                       // 2: mediaflow.thumbnail.Job
	(*GenerateThumbnailRequest)(nil),  // 3: mediaflow.thumbnail.GenerateThumbnailRequest
	(*GenerateThumbnailResponse)(nil), // 4: mediaflow.thumbnail.GenerateThumbnailResponse
	(*GetJobRequest)(nil),             // 5: mediaflow.thumbnail.GetJobRequest
	(*ThumbnailGenerated)(nil),        // 6: mediaflow.thumbnail.ThumbnailGenerated
	(*ThumbnailFailed)(nil),           // 7: mediaflow.thumbnail.ThumbnailFailed
	(common.Status)(0),                // 8: mediaflow.common.Status
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*common.Error)(nil),              // 10: mediaflow.common.Error
}
var file_thumbnail_thumbnail_proto_depIdxs = []int32{
	0,  // 0: mediaflow.thumbnail.Job.strategy:type_name -> mediaflow.thumbnail.Strategy
	8,  // 1: mediaflow.thumbnail.Job.status:type_name -> mediaflow.common.Status
	1,  // 2: mediaflow.thumbnail.Job.thumbnails:type_name -> mediaflow.thumbnail.Thumbnail
	9,  // 3: mediaflow.thumbnail.Job.started_at:type_name -> google.protobuf.Timestamp
	9,  // 4: mediaflow.thumbnail.Job.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 5: mediaflow.thumbnail.GenerateThumbnailRequest.strategy:type_name -> mediaflow.thumbnail.Strategy
	2,  // 6: mediaflow.thumbnail.GenerateThumbnailResponse.job:type_name -> mediaflow.thumbnail.Job
	1,  // 7: mediaflow.thumbnail.ThumbnailGenerated.thumbnails:type_name -> mediaflow.thumbnail.Thumbnail
	9,  // 8: mediaflow.thumbnail.ThumbnailGenerated.generated_at:type_name -> google.protobuf.Timestamp
	10, // 9: mediaflow.thumbnail.ThumbnailFailed.error:type_name -> mediaflow.common.Error
	3,  // 10: mediaflow.thumbnail.ThumbnailService.GenerateThumbnail:input_type -> mediaflow.thumbnail.GenerateThumbnailRequest
	5,  // 11: mediaflow.thumbnail.ThumbnailService.GetJob:input_type -> mediaflow.thumbnail.GetJobRequest
	4,  // 12: mediaflow.thumbnail.ThumbnailService.GenerateThumbnail:output_type -> mediaflow.thumbnail.GenerateThumbnailResponse
	2,  // 13: mediaflow.thumbnail.ThumbnailService.GetJob:output_type -> mediaflow.thumbnail.Job
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_thumbnail_thumbnail_proto_init() }
func file_thumbnail_thumbnail_proto_init() {
	if File_thumbnail_thumbnail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thumbnail_thumbnail_proto_rawDesc), len(file_thumbnail_thumbnail_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thumbnail_thumbnail_proto_goTypes,
		DependencyIndexes: file_thumbnail_thumbnail_proto_depIdxs,
		EnumInfos:         file_thumbnail_thumbnail_proto_enumTypes,
		MessageInfos:      file_thumbnail_thumbnail_proto_msgTypes,
	}.Build()
	File_thumbnail_thumbnail_proto = out.File
	file_thumbnail_thumbnail_proto_goTypes = nil
	file_thumbnail_thumbnail_proto_depIdxs = nil
}
