// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.23.3
// source: transcoding/v1/transcoding.proto

package transcodingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscodingService_TranscodeNow_FullMethodName = "/mediaflow.transcoding.v1.TranscodingService/TranscodeNow"
	TranscodingService_GetJob_FullMethodName       = "/mediaflow.transcoding.v1.TranscodingService/GetJob"
)

// TranscodingServiceClient is the client API for TranscodingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscodingServiceClient interface {
	TranscodeNow(ctx context.Context, in *TranscodeNowRequest, opts ...grpc.CallOption) (*TranscodeNowResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error)
}

type transcodingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscodingServiceClient(cc grpc.ClientConnInterface) TranscodingServiceClient {
	return &transcodingServiceClient{cc}
}

func (c *transcodingServiceClient) TranscodeNow(ctx context.Context, in *TranscodeNowRequest, opts ...grpc.CallOption) (*TranscodeNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscodeNowResponse)
	err := c.cc.Invoke(ctx, TranscodingService_TranscodeNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodingServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, TranscodingService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscodingServiceServer is the server API for TranscodingService service.
// All implementations must embed UnimplementedTranscodingServiceServer
// for forward compatibility.
type TranscodingServiceServer interface {
	TranscodeNow(context.Context, *TranscodeNowRequest) (*TranscodeNowResponse, error)
	GetJob(context.Context, *GetJobRequest) (*Job, error)
	mustEmbedUnimplementedTranscodingServiceServer()
}

// UnimplementedTranscodingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscodingServiceServer struct{}

func (UnimplementedTranscodingServiceServer) TranscodeNow(context.Context, *TranscodeNowRequest) (*TranscodeNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscodeNow not implemented")
}
func (UnimplementedTranscodingServiceServer) GetJob(context.Context, *GetJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedTranscodingServiceServer) mustEmbedUnimplementedTranscodingServiceServer() {}
func (UnimplementedTranscodingServiceServer) testEmbeddedByValue()                            {}

// UnsafeTranscodingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscodingServiceServer will
// result in compilation errors.
type UnsafeTranscodingServiceServer interface {
	mustEmbedUnimplementedTranscodingServiceServer()
}

func RegisterTranscodingServiceServer(s grpc.ServiceRegistrar, srv TranscodingServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscodingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscodingService_ServiceDesc, srv)
}

func _TranscodingService_TranscodeNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscodeNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodingServiceServer).TranscodeNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodingService_TranscodeNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodingServiceServer).TranscodeNow(ctx, req.(*TranscodeNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodingService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodingServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodingService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodingServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscodingService_ServiceDesc is the grpc.ServiceDesc for TranscodingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscodingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediaflow.transcoding.v1.TranscodingService",
	HandlerType: (*TranscodingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranscodeNow",
			Handler:    _TranscodingService_TranscodeNow_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _TranscodingService_GetJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transcoding/v1/transcoding.proto",
}
