// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: transcoding/v1/transcoding.proto

package transcodingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "mediaflow/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile describes a target rendition (codec + container + resolution).
type Profile int32

const (
	Profile_PROFILE_UNSPECIFIED Profile = 0
	Profile_PROFILE_HLS_240P    Profile = 1
	Profile_PROFILE_HLS_480P    Profile = 2
	Profile_PROFILE_HLS_720P    Profile = 3
	Profile_PROFILE_HLS_1080P   Profile = 4
	Profile_PROFILE_DASH_1080P  Profile = 5
)

// Enum value maps for Profile.
var (
	Profile_name = map[int32]string{
		0: "PROFILE_UNSPECIFIED",
		1: "PROFILE_HLS_240P",
		2: "PROFILE_HLS_480P",
		3: "PROFILE_HLS_720P",
		4: "PROFILE_HLS_1080P",
		5: "PROFILE_DASH_1080P",
	}
	Profile_value = map[string]int32{
		"PROFILE_UNSPECIFIED": 0,
		"PROFILE_HLS_240P":    1,
		"PROFILE_HLS_480P":    2,
		"PROFILE_HLS_720P":    3,
		"PROFILE_HLS_1080P":   4,
		"PROFILE_DASH_1080P":  5,
	}
)

func (x Profile) Enum() *Profile {
	p := new(Profile)
	*p = x
	return p
}

func (x Profile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Profile) Descriptor() protoreflect.EnumDescriptor {
	return file_transcoding_v1_transcoding_proto_enumTypes[0].Descriptor()
}

func (Profile) Type() protoreflect.EnumType {
	return &file_transcoding_v1_transcoding_proto_enumTypes[0]
}

func (x Profile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Profile.Descriptor instead.
func (Profile) EnumDescriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{0}
}

// Variant is one produced rendition stored back to S3.
type Variant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         Profile                `protobuf:"varint,1,opt,name=profile,proto3,enum=mediaflow.transcoding.v1.Profile" json:"profile,omitempty"`
	S3Bucket        string                 `protobuf:"bytes,2,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Key           string                 `protobuf:"bytes,3,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Width           int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height          int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	BitrateKbps     int32                  `protobuf:"varint,7,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{0}
}

func (x *Variant) GetProfile() Profile {
	if x != nil {
		return x.Profile
	}
	return Profile_PROFILE_UNSPECIFIED
}

func (x *Variant) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *Variant) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Variant) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Variant) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Variant) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Variant) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *Variant) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// Job is the persisted transcoding work item, one row per (media_id, profile).
type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,3,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Profile       Profile                `protobuf:"varint,4,opt,name=profile,proto3,enum=mediaflow.transcoding.v1.Profile" json:"profile,omitempty"`
	Status        v1.Status              `protobuf:"varint,5,opt,name=status,proto3,enum=mediaflow.common.v1.Status" json:"status,omitempty"`
	Output        *Variant               `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Attempt       int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Job) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *Job) GetProfile() Profile {
	if x != nil {
		return x.Profile
	}
	return Profile_PROFILE_UNSPECIFIED
}

func (x *Job) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *Job) GetOutput() *Variant {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// TranscodeNow is intended for ops/manual reruns. The normal path is
// event-driven via saga.cmd.transcode.v1.
type TranscodeNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SourceS3Key   string                 `protobuf:"bytes,2,opt,name=source_s3_key,json=sourceS3Key,proto3" json:"source_s3_key,omitempty"`
	Profiles      []Profile              `protobuf:"varint,3,rep,packed,name=profiles,proto3,enum=mediaflow.transcoding.v1.Profile" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeNowRequest) Reset() {
	*x = TranscodeNowRequest{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeNowRequest) ProtoMessage() {}

func (x *TranscodeNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeNowRequest.ProtoReflect.Descriptor instead.
func (*TranscodeNowRequest) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{2}
}

func (x *TranscodeNowRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *TranscodeNowRequest) GetSourceS3Key() string {
	if x != nil {
		return x.SourceS3Key
	}
	return ""
}

func (x *TranscodeNowRequest) GetProfiles() []Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type TranscodeNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeNowResponse) Reset() {
	*x = TranscodeNowResponse{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeNowResponse) ProtoMessage() {}

func (x *TranscodeNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeNowResponse.ProtoReflect.Descriptor instead.
func (*TranscodeNowResponse) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{3}
}

func (x *TranscodeNowResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type TranscodingStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Profile       Profile                `protobuf:"varint,2,opt,name=profile,proto3,enum=mediaflow.transcoding.v1.Profile" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodingStarted) Reset() {
	*x = TranscodingStarted{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodingStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodingStarted) ProtoMessage() {}

func (x *TranscodingStarted) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodingStarted.ProtoReflect.Descriptor instead.
func (*TranscodingStarted) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{5}
}

func (x *TranscodingStarted) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *TranscodingStarted) GetProfile() Profile {
	if x != nil {
		return x.Profile
	}
	return Profile_PROFILE_UNSPECIFIED
}

type TranscodingCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Variants      []*Variant             `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodingCompleted) Reset() {
	*x = TranscodingCompleted{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodingCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodingCompleted) ProtoMessage() {}

func (x *TranscodingCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodingCompleted.ProtoReflect.Descriptor instead.
func (*TranscodingCompleted) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{6}
}

func (x *TranscodingCompleted) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *TranscodingCompleted) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *TranscodingCompleted) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type TranscodingFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Profile       Profile                `protobuf:"varint,2,opt,name=profile,proto3,enum=mediaflow.transcoding.v1.Profile" json:"profile,omitempty"`
	Error         *v1.Error              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodingFailed) Reset() {
	*x = TranscodingFailed{}
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodingFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodingFailed) ProtoMessage() {}

func (x *TranscodingFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transcoding_v1_transcoding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodingFailed.ProtoReflect.Descriptor instead.
func (*TranscodingFailed) Descriptor() ([]byte, []int) {
	return file_transcoding_v1_transcoding_proto_rawDescGZIP(), []int{7}
}

func (x *TranscodingFailed) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *TranscodingFailed) GetProfile() Profile {
	if x != nil {
		return x.Profile
	}
	return Profile_PROFILE_UNSPECIFIED
}

func (x *TranscodingFailed) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TranscodingFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_transcoding_v1_transcoding_proto protoreflect.FileDescriptor

const file_transcoding_v1_transcoding_proto_rawDesc = "" +
	"\n" +
	" transcoding/v1/transcoding.proto\x12\x18mediaflow.transcoding.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\x95\x02\n" +
	"\aVariant\x12;\n" +
	"\aprofile\x18\x01 \x01(\x0e2!.mediaflow.transcoding.v1.ProfileR\aprofile\x12\x1b\n" +
	"\ts3_bucket\x18\x02 \x01(\tR\bs3Bucket\x12\x15\n" +
	"\x06s3_key\x18\x03 \x01(\tR\x05s3Key\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12!\n" +
	"\fbitrate_kbps\x18\a \x01(\x05R\vbitrateKbps\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x01R\x0fdurationSeconds\"\xae\x03\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x17\n" +
	"\asaga_id\x18\x03 \x01(\tR\x06sagaId\x12;\n" +
	"\aprofile\x18\x04 \x01(\x0e2!.mediaflow.transcoding.v1.ProfileR\aprofile\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.mediaflow.common.v1.StatusR\x06status\x129\n" +
	"\x06output\x18\x06 \x01(\v2!.mediaflow.transcoding.v1.VariantR\x06output\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\x93\x01\n" +
	"\x13TranscodeNowRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\"\n" +
	"\rsource_s3_key\x18\x02 \x01(\tR\vsourceS3Key\x12=\n" +
	"\bprofiles\x18\x03 \x03(\x0e2!.mediaflow.transcoding.v1.ProfileR\bprofiles\"I\n" +
	"\x14TranscodeNowResponse\x121\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1d.mediaflow.transcoding.v1.JobR\x04jobs\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"l\n" +
	"\x12TranscodingStarted\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12;\n" +
	"\aprofile\x18\x02 \x01(\x0e2!.mediaflow.transcoding.v1.ProfileR\aprofile\"\xaf\x01\n" +
	"\x14TranscodingCompleted\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12=\n" +
	"\bvariants\x18\x02 \x03(\v2!.mediaflow.transcoding.v1.VariantR\bvariants\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xb7\x01\n" +
	"\x11TranscodingFailed\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12;\n" +
	"\aprofile\x18\x02 \x01(\x0e2!.mediaflow.transcoding.v1.ProfileR\aprofile\x120\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.mediaflow.common.v1.ErrorR\x05error\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt*\x93\x01\n" +
	"\aProfile\x12\x17\n" +
	"\x13PROFILE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PROFILE_HLS_240P\x10\x01\x12\x14\n" +
	"\x10PROFILE_HLS_480P\x10\x02\x12\x14\n" +
	"\x10PROFILE_HLS_720P\x10\x03\x12\x15\n" +
	"\x11PROFILE_HLS_1080P\x10\x04\x12\x16\n" +
	"\x12PROFILE_DASH_1080P\x10\x052\xd5\x01\n" +
	"\x12TranscodingService\x12m\n" +
	"\fTranscodeNow\x12-.mediaflow.transcoding.v1.TranscodeNowRequest\x1a..mediaflow.transcoding.v1.TranscodeNowResponse\x12P\n" +
	"\x06GetJob\x12'.mediaflow.transcoding.v1.GetJobRequest\x1a\x1d.mediaflow.transcoding.v1.JobB.Z,mediaflow/proto/transcoding/v1;transcodingv1b\x06proto3"

var (
	file_transcoding_v1_transcoding_proto_rawDescOnce sync.Once
	file_transcoding_v1_transcoding_proto_rawDescData []byte
)

func file_transcoding_v1_transcoding_proto_rawDescGZIP() []byte {
	file_transcoding_v1_transcoding_proto_rawDescOnce.Do(func() {
		file_transcoding_v1_transcoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoding_v1_transcoding_proto_rawDesc), len(file_transcoding_v1_transcoding_proto_rawDesc)))
	})
	return file_transcoding_v1_transcoding_proto_rawDescData
}

var file_transcoding_v1_transcoding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transcoding_v1_transcoding_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transcoding_v1_transcoding_proto_goTypes = []any{
	(Profile)(0),                  // 0: mediaflow.transcoding.v1.Profile
	(*Variant)(nil),               // 1: mediaflow.transcoding.v1.Variant
	(*Job)(nil),                   // 2: mediaflow.transcoding.v1.Job
	(*TranscodeNowRequest)(nil),   // 3: mediaflow.transcoding.v1.TranscodeNowRequest
	(*TranscodeNowResponse)(nil),  // 4: mediaflow.transcoding.v1.TranscodeNowResponse
	(*GetJobRequest)(nil),         // 5: mediaflow.transcoding.v1.GetJobRequest
	(*TranscodingStarted)(nil),    // 6: mediaflow.transcoding.v1.TranscodingStarted
	(*TranscodingCompleted)(nil),  // 7: mediaflow.transcoding.v1.TranscodingCompleted
	(*TranscodingFailed)(nil),     // 8: mediaflow.transcoding.v1.TranscodingFailed
	(v1.Status)(0),                // 9: mediaflow.common.v1.Status
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*v1.Error)(nil),              // 11: mediaflow.common.v1.Error
}
var file_transcoding_v1_transcoding_proto_depIdxs = []int32{
	0,  // 0: mediaflow.transcoding.v1.Variant.profile:type_name -> mediaflow.transcoding.v1.Profile
	0,  // 1: mediaflow.transcoding.v1.Job.profile:type_name -> mediaflow.transcoding.v1.Profile
	9,  // 2: mediaflow.transcoding.v1.Job.status:type_name -> mediaflow.common.v1.Status
	1,  // 3: mediaflow.transcoding.v1.Job.output:type_name -> mediaflow.transcoding.v1.Variant
	10, // 4: mediaflow.transcoding.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	10, // 5: mediaflow.transcoding.v1.Job.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 6: mediaflow.transcoding.v1.TranscodeNowRequest.profiles:type_name -> mediaflow.transcoding.v1.Profile
	2,  // 7: mediaflow.transcoding.v1.TranscodeNowResponse.jobs:type_name -> mediaflow.transcoding.v1.Job
	0,  // 8: mediaflow.transcoding.v1.TranscodingStarted.profile:type_name -> mediaflow.transcoding.v1.Profile
	1,  // 9: mediaflow.transcoding.v1.TranscodingCompleted.variants:type_name -> mediaflow.transcoding.v1.Variant
	10, // 10: mediaflow.transcoding.v1.TranscodingCompleted.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 11: mediaflow.transcoding.v1.TranscodingFailed.profile:type_name -> mediaflow.transcoding.v1.Profile
	11, // 12: mediaflow.transcoding.v1.TranscodingFailed.error:type_name -> mediaflow.common.v1.Error
	3,  // 13: mediaflow.transcoding.v1.TranscodingService.TranscodeNow:input_type -> mediaflow.transcoding.v1.TranscodeNowRequest
	5,  // 14: mediaflow.transcoding.v1.TranscodingService.GetJob:input_type -> mediaflow.transcoding.v1.GetJobRequest
	4,  // 15: mediaflow.transcoding.v1.TranscodingService.TranscodeNow:output_type -> mediaflow.transcoding.v1.TranscodeNowResponse
	2,  // 16: mediaflow.transcoding.v1.TranscodingService.GetJob:output_type -> mediaflow.transcoding.v1.Job
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_transcoding_v1_transcoding_proto_init() }
func file_transcoding_v1_transcoding_proto_init() {
	if File_transcoding_v1_transcoding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoding_v1_transcoding_proto_rawDesc), len(file_transcoding_v1_transcoding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoding_v1_transcoding_proto_goTypes,
		DependencyIndexes: file_transcoding_v1_transcoding_proto_depIdxs,
		EnumInfos:         file_transcoding_v1_transcoding_proto_enumTypes,
		MessageInfos:      file_transcoding_v1_transcoding_proto_msgTypes,
	}.Build()
	File_transcoding_v1_transcoding_proto = out.File
	file_transcoding_v1_transcoding_proto_goTypes = nil
	file_transcoding_v1_transcoding_proto_depIdxs = nil
}
