// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: upload/upload.proto

package upload

import (
	common "github.com/tolgafiratoglu/mediaflow/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Upload represents a single client-initiated upload session. It is created
// when a presigned URL is issued and transitions to UPLOADED once the client
// confirms the S3 PUT completed. From there, a Media aggregate is created
// and the saga is started.
type Upload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	S3Bucket      string                 `protobuf:"bytes,6,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Key         string                 `protobuf:"bytes,7,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Status        common.Status          `protobuf:"varint,8,opt,name=status,proto3,enum=mediaflow.common.Status" json:"status,omitempty"`
	MediaId       string                 `protobuf:"bytes,9,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"` // populated after confirm
	SagaId        string                 `protobuf:"bytes,10,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`   // populated after confirm
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Audit         *common.Audit          `protobuf:"bytes,12,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upload) Reset() {
	*x = Upload{}
	mi := &file_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upload) ProtoMessage() {}

func (x *Upload) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upload.ProtoReflect.Descriptor instead.
func (*Upload) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *Upload) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *Upload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Upload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Upload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Upload) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Upload) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *Upload) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Upload) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *Upload) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Upload) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *Upload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Upload) GetAudit() *common.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type CreatePresignedUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePresignedUploadRequest) Reset() {
	*x = CreatePresignedUploadRequest{}
	mi := &file_upload_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePresignedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresignedUploadRequest) ProtoMessage() {}

func (x *CreatePresignedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresignedUploadRequest.ProtoReflect.Descriptor instead.
func (*CreatePresignedUploadRequest) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePresignedUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CreatePresignedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                                                                   // presigned PUT URL
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // headers the client must send
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePresignedUploadResponse) Reset() {
	*x = CreatePresignedUploadResponse{}
	mi := &file_upload_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePresignedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresignedUploadResponse) ProtoMessage() {}

func (x *CreatePresignedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresignedUploadResponse.ProtoReflect.Descriptor instead.
func (*CreatePresignedUploadResponse) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePresignedUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CreatePresignedUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreatePresignedUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreatePresignedUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmUploadRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UploadId string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// ETag returned by S3, used for integrity verification.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_upload_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,2,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Status        common.Status          `protobuf:"varint,3,opt,name=status,proto3,enum=mediaflow.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_upload_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ConfirmUploadResponse) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *ConfirmUploadResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

type GetUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadRequest) Reset() {
	*x = GetUploadRequest{}
	mi := &file_upload_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadRequest) ProtoMessage() {}

func (x *GetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadRequest.ProtoReflect.Descriptor instead.
func (*GetUploadRequest) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{5}
}

func (x *GetUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type CancelUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadRequest) Reset() {
	*x = CancelUploadRequest{}
	mi := &file_upload_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadRequest) ProtoMessage() {}

func (x *CancelUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadRequest.ProtoReflect.Descriptor instead.
func (*CancelUploadRequest) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{6}
}

func (x *CancelUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CancelUploadRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.Status          `protobuf:"varint,1,opt,name=status,proto3,enum=mediaflow.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadResponse) Reset() {
	*x = CancelUploadResponse{}
	mi := &file_upload_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadResponse) ProtoMessage() {}

func (x *CancelUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadResponse.ProtoReflect.Descriptor instead.
func (*CancelUploadResponse) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{7}
}

func (x *CancelUploadResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

// MediaUploaded is produced when ConfirmUpload succeeds. Partition key on
// Kafka is media_id so that all subsequent events for the same media are
// processed in order by a single consumer instance.
type MediaUploaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	S3Bucket      string                 `protobuf:"bytes,4,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Key         string                 `protobuf:"bytes,5,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploaded) Reset() {
	*x = MediaUploaded{}
	mi := &file_upload_upload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploaded) ProtoMessage() {}

func (x *MediaUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploaded.ProtoReflect.Descriptor instead.
func (*MediaUploaded) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{8}
}

func (x *MediaUploaded) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaUploaded) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *MediaUploaded) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaUploaded) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *MediaUploaded) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *MediaUploaded) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaUploaded) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaUploaded) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type UploadCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCancelled) Reset() {
	*x = UploadCancelled{}
	mi := &file_upload_upload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCancelled) ProtoMessage() {}

func (x *UploadCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCancelled.ProtoReflect.Descriptor instead.
func (*UploadCancelled) Descriptor() ([]byte, []int) {
	return file_upload_upload_proto_rawDescGZIP(), []int{9}
}

func (x *UploadCancelled) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_upload_upload_proto protoreflect.FileDescriptor

const file_upload_upload_proto_rawDesc = "" +
	"\n" +
	"\x13upload/upload.proto\x12\x10mediaflow.upload\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xa1\x03\n" +
	"\x06Upload\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\ts3_bucket\x18\x06 \x01(\tR\bs3Bucket\x12\x15\n" +
	"\x06s3_key\x18\a \x01(\tR\x05s3Key\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.mediaflow.common.StatusR\x06status\x12\x19\n" +
	"\bmedia_id\x18\t \x01(\tR\amediaId\x12\x17\n" +
	"\asaga_id\x18\n" +
	" \x01(\tR\x06sagaId\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12-\n" +
	"\x05audit\x18\f \x01(\v2\x17.mediaflow.common.AuditR\x05audit\"\x96\x01\n" +
	"\x1cCreatePresignedUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x9d\x02\n" +
	"\x1dCreatePresignedUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12V\n" +
	"\aheaders\x18\x03 \x03(\v2<.mediaflow.upload.CreatePresignedUploadResponse.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14ConfirmUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"}\n" +
	"\x15ConfirmUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x17\n" +
	"\asaga_id\x18\x02 \x01(\tR\x06sagaId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.mediaflow.common.StatusR\x06status\"/\n" +
	"\x10GetUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"J\n" +
	"\x13CancelUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x14CancelUploadResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.mediaflow.common.StatusR\x06status\"\x93\x02\n" +
	"\rMediaUploaded\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\ts3_bucket\x18\x04 \x01(\tR\bs3Bucket\x12\x15\n" +
	"\x06s3_key\x18\x05 \x01(\tR\x05s3Key\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12;\n" +
	"\vuploaded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"F\n" +
	"\x0fUploadCancelled\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x95\x03\n" +
	"\rUploadService\x12x\n" +
	"\x15CreatePresignedUpload\x12..mediaflow.upload.CreatePresignedUploadRequest\x1a/.mediaflow.upload.CreatePresignedUploadResponse\x12`\n" +
	"\rConfirmUpload\x12&.mediaflow.upload.ConfirmUploadRequest\x1a'.mediaflow.upload.ConfirmUploadResponse\x12I\n" +
	"\tGetUpload\x12\".mediaflow.upload.GetUploadRequest\x1a\x18.mediaflow.upload.Upload\x12]\n" +
	"\fCancelUpload\x12%.mediaflow.upload.CancelUploadRequest\x1a&.mediaflow.upload.CancelUploadResponseB9Z7github.com/tolgafiratoglu/mediaflow/proto/upload;uploadb\x06proto3"

var (
	file_upload_upload_proto_rawDescOnce sync.Once
	file_upload_upload_proto_rawDescData []byte
)

func file_upload_upload_proto_rawDescGZIP() []byte {
	file_upload_upload_proto_rawDescOnce.Do(func() {
		file_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_upload_proto_rawDesc), len(file_upload_upload_proto_rawDesc)))
	})
	return file_upload_upload_proto_rawDescData
}

var file_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_upload_upload_proto_goTypes = []any{
	(*Upload)(nil),                        // 0: mediaflow.upload.Upload
	(*CreatePresignedUploadRequest)(nil),  // 1: mediaflow.upload.CreatePresignedUploadRequest
	(*CreatePresignedUploadResponse)(nil), // 2: mediaflow.upload.CreatePresignedUploadResponse
	(*ConfirmUploadRequest)(nil),          // 3: mediaflow.upload.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),         // 4: mediaflow.upload.ConfirmUploadResponse
	(*GetUploadRequest)(nil),              // 5: mediaflow.upload.GetUploadRequest
	(*CancelUploadRequest)(nil),           // 6: mediaflow.upload.CancelUploadRequest
	(*CancelUploadResponse)(nil),          // 7: mediaflow.upload.CancelUploadResponse
	(*MediaUploaded)(nil),                 // 8: mediaflow.upload.MediaUploaded
	(*UploadCancelled)(nil),               // 9: mediaflow.upload.UploadCancelled
	nil,                                   // 10: mediaflow.upload.CreatePresignedUploadResponse.HeadersEntry
	(common.Status)(0),                    // 11: mediaflow.common.Status
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*common.Audit)(nil),                  // 13: mediaflow.common.Audit
}
var file_upload_upload_proto_depIdxs = []int32{
	11, // 0: mediaflow.upload.Upload.status:type_name -> mediaflow.common.Status
	12, // 1: mediaflow.upload.Upload.expires_at:type_name -> google.protobuf.Timestamp
	13, // 2: mediaflow.upload.Upload.audit:type_name -> mediaflow.common.Audit
	10, // 3: mediaflow.upload.CreatePresignedUploadResponse.headers:type_name -> mediaflow.upload.CreatePresignedUploadResponse.HeadersEntry
	12, // 4: mediaflow.upload.CreatePresignedUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 5: mediaflow.upload.ConfirmUploadResponse.status:type_name -> mediaflow.common.Status
	11, // 6: mediaflow.upload.CancelUploadResponse.status:type_name -> mediaflow.common.Status
	12, // 7: mediaflow.upload.MediaUploaded.uploaded_at:type_name -> google.protobuf.Timestamp
	1,  // 8: mediaflow.upload.UploadService.CreatePresignedUpload:input_type -> mediaflow.upload.CreatePresignedUploadRequest
	3,  // 9: mediaflow.upload.UploadService.ConfirmUpload:input_type -> mediaflow.upload.ConfirmUploadRequest
	5,  // 10: mediaflow.upload.UploadService.GetUpload:input_type -> mediaflow.upload.GetUploadRequest
	6,  // 11: mediaflow.upload.UploadService.CancelUpload:input_type -> mediaflow.upload.CancelUploadRequest
	2,  // 12: mediaflow.upload.UploadService.CreatePresignedUpload:output_type -> mediaflow.upload.CreatePresignedUploadResponse
	4,  // 13: mediaflow.upload.UploadService.ConfirmUpload:output_type -> mediaflow.upload.ConfirmUploadResponse
	0,  // 14: mediaflow.upload.UploadService.GetUpload:output_type -> mediaflow.upload.Upload
	7,  // 15: mediaflow.upload.UploadService.CancelUpload:output_type -> mediaflow.upload.CancelUploadResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_upload_upload_proto_init() }
func file_upload_upload_proto_init() {
	if File_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_upload_proto_rawDesc), len(file_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upload_upload_proto_goTypes,
		DependencyIndexes: file_upload_upload_proto_depIdxs,
		MessageInfos:      file_upload_upload_proto_msgTypes,
	}.Build()
	File_upload_upload_proto = out.File
	file_upload_upload_proto_goTypes = nil
	file_upload_upload_proto_depIdxs = nil
}
